import React from 'react'
import './Webpage.css'
const Webpage = () => {
  return (
    <div>
        <p></p>
        <h1>This is a Webpage</h1>
        <h5>Use the tool Annotate tool</h5>
        <p style={{backgroundColor: '#333', width:'device-width'}}>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A doloribus nihil possimus vitae rem. Ea officia provident dolorem nisi impedit reprehenderit? Est ipsam maxime tenetur sed nam eaque, hic officiis. Veniam id dignissimos corrupti, incidunt, autem eos dicta tenetur magni asperiores porro consequatur quaerat ut sed maiores quibusdam minus ratione.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Numquam veritatis modi libero excepturi earum ipsum id pariatur iusto, temporibus quo saepe cum tempora expedita accusantium dignissimos ducimus. Odit, minus, rerum atque minima repellendus ducimus hic molestiae nihil vero id blanditiis nam voluptatem earum assumenda voluptatibus recusandae laborum voluptate beatae architecto quisquam nobis laudantium! Porro, corporis? Pariatur necessitatibus illum dolor velit error beatae quia eveniet quibusdam delectus debitis officia nobis obcaecati, sit iure maiores aperiam enim optio repellendus sint molestiae porro. Esse totam harum rem dolore, aliquid corporis fugit in laudantium obcaecati id, quidem illum officia aperiam optio soluta. Eum, unde.</p> 
        <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Excepturi maxime esse sit alias a eum repudiandae error beatae numquam nostrum quos dolores suscipit, neque placeat magnam sequi sapiente eos est!</p>
        <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptatibus, iste quos assumenda doloribus officiis quaerat voluptates laboriosam. Voluptatem, nulla ab?</p>
        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Incidunt impedit libero error, nihil vitae voluptas assumenda ab aspernatur consequuntur culpa dolor! Saepe ratione sint debitis atque impedit doloremque ex fugit dolores, sapiente quia earum cupiditate illum explicabo non facilis accusamus ad deleniti asperiores eligendi quidem veniam obcaecati eaque. Optio at eaque voluptas, facilis incidunt officiis a dolores expedita obcaecati magni repellat? Rerum ratione perspiciatis ad magni, explicabo consequatur earum repellat cum, at omnis ullam fuga nostrum soluta odit eveniet aperiam? Rerum architecto debitis nostrum optio tempore ipsum impedit consequuntur quasi assumenda eaque, nisi odio? Error ea facilis vero, perferendis molestias qui ratione aut minus cum quisquam autem id dicta iste esse soluta! Eum blanditiis quod placeat vero aliquid sed. Commodi repellat nulla eveniet beatae doloremque! Libero distinctio quod itaque esse omnis, voluptas beatae temporibus dolorem amet delectus a at error quos enim vero! Id nisi veniam voluptas sequi cum eum atque est, molestias minus harum eligendi sunt? Explicabo aperiam quia soluta magni nesciunt enim itaque voluptatum eius molestiae accusamus beatae minima magnam, esse temporibus architecto ducimus dolorem? Quae vel magnam eligendi iure quos est, sapiente numquam, odit a quaerat ipsa temporibus, in sit? Enim quidem rerum explicabo harum est velit consequatur ea tempora perspiciatis minima provident doloremque voluptatibus voluptatem doloribus nisi ab aut, assumenda nesciunt consectetur accusamus laudantium dicta alias excepturi quam! Fuga aliquid ipsum dolorem ullam quia laudantium dolore natus architecto! Modi maiores, quae, ex numquam dolor aspernatur eveniet quis voluptate totam ut nobis unde earum inventore est qui laudantium distinctio. Architecto repellendus ad aliquid, expedita soluta iure inventore dolorum impedit voluptate dolores mollitia facere amet molestiae reiciendis nostrum voluptatibus iste provident at eum ex. Natus beatae laudantium omnis nisi porro officiis, quia sed eveniet, unde ipsa magnam suscipit. Voluptatibus ad debitis nulla praesentium magni eligendi eveniet non! Quasi sequi non, explicabo, ipsa beatae sed harum labore qui consectetur iste dolores omnis quidem, vitae tenetur autem et similique maiores in natus maxime tempora ipsum necessitatibus? Quisquam magni maiores tempora est sunt delectus eligendi nam doloremque, quas ducimus corrupti a praesentium fuga eveniet explicabo facilis alias labore exercitationem numquam beatae harum quis quaerat eaque ea. Temporibus veritatis quibusdam ad, placeat voluptatibus non eum vel earum voluptate fugiat. Asperiores perferendis exercitationem, in necessitatibus sint sunt maiores odit minus labore perspiciatis quibusdam a illum ut, est molestiae quam placeat harum repellat ad obcaecati velit. Voluptate blanditiis, veritatis nesciunt placeat quam voluptatibus a!</p>
    </div>
  )
}

export default Webpage